# n_config.yaml

# common defaults for most technologies
base: &base
  initial capacity: 0 # default initial capacity null
  expansion: true # default capacity expansion
  cost factor: 1  # default to input source
  max capacity: .inf   # default to infinity

# -------------------  config (alphabetical) -------------------
# Units refer to bus0 in the network except for 'biogas'
battery:
  <<: *base

battery inverter:
  <<: *base

biogas:
  <<: *base

biogas storage:
  <<: *base
  max capacity: 200 # MWh

biogas upgrading:
  <<: *base

biomass belt dryer:
  <<: *base
  cost factor: 1.2       # override

biomass boiler:
  <<: *base

biomethanation biogas:
  <<: *base

biomethanation CO2:
  <<: *base

cat methanation biogas:
  <<: *base

cat methanation CO2:
  <<: *base

CO2 compressor:
  <<: *base

CO2 HP storage:
  <<: *base

CO2 Liq:
  <<: *base

CO2 Liq storage:
  <<: *base

CO2 pipe:
  <<: *base

dewatering:
  <<: *base

El boiler:
  <<: *base

electrolysis:
  <<: *base
  cost factor: 2                        # override

DH heat exchanger:
  <<: *base

eSMR meoh:
  <<: *base

grid connection:
  <<: *base

H2 compressor:
  <<: *base
  cost factor: 2                        # override

H2 pipe:
  <<: *base

H2 storage:
  <<: *base


heat pump:
  <<: *base

meoh:
  <<: *base

NG boiler:
  <<: *base

onwind:
  <<: *base

pelletization:
  <<: *base

pyrolysis:
  <<: *base

solar:
  <<: *base

TES concrete:
  <<: *base

TES DH:
  <<: *base
