# Any content on this file will override config/config_default.yaml
# Use it for customization of the model


###### Enter content below this line #####
run_name: price_price_noRE

targets:
  driver: 'price' # 'price' | 'demand'

# Network configuration flags
n_flags:
  biogas: true
  central_heat: false
  renewables: false
  electrolysis: true
  meoh: false
  methanation: true
  symbiosis: true   # all internal connection between plants (El, H2, CO2, Heat MT, DH, LT)
  storage: true     # activate every Thermal and Battery storage (from n_config)
  print: true       # saves svg of prenetwork before optimization
  export: false     # exports prenetwork before optimization -> always saved in resources/

# RFNBOs
rfnbos_dict:
  limit: 'price'         # emissions | price | unlimited | disconnected

# SOLVER
optimization:
  solver :  'gurobi'  # 'gurobi' | 'highs'
  solver_profile : "gurobi-barrier-fast" # (DEFAULT FOR SPEED ON LOCAL MACHINE) select from scripts.solver_profiles.py
  collect_all_duals: true  #  saves all dual variables also those form custom constraints -->
  return_model: true  # returns linopy model