# Any content on this file will override config/config_default.yaml
# Use it for customization of the model


###### Enter content below this line #####
run_name: BF_test_flex_D

targets:
  driver: 'price' # 'price' | 'demand'

# RFNBOs
rfnbos_dict:
  limit: 'price'         # emissions | price | unlimited | disconnected

amortization_period: 8

# SOLVER
optimization:
  solver :  'gurobi'  # 'gurobi' | 'highs'
  solver_profile : "gurobi-barrier-fast" # (DEFAULT FOR SPEED ON LOCAL MACHINE) select from scripts.solver_profiles.py
  collect_all_duals: true  #  saves all dual variables also those form custom constraints -->
  return_model: true  # returns linopy model