# config/config.yml
run_name: full_test

# CO2 tax for fossil emissions and reward for negative emissions
CO2_cost: 150 # €/t (CO2_cost)
# Others
CO2_cost_ref_year: 0

# Annual Demands inputs
flh_H2: 4000 # full load hours / y
H2_output: 68 # nominal capacity (H2)
flh_Biogas: 8760 # full load hours / y
biogas_output: 27 # nominal capacity (ch4)
flh_meoh: 2000 # full load hours / y
meoh_output: 8 # nominal capacity (meoh)

# Sales of Electricity
el_DK1_sale_el_RFNBO: 0.3 # max share of RE production that can be sold to ElDK1

# Energy & Weather year
En_price_year: 2024
preprocess_flag: false

# Location
latitude: 56.566
longitude: 9.033

# Network configuration flags
n_flags:
  biogas: true
  central_heat: true
  renewables: true
  electrolysis: true
  meoh: true
  methanation: true
  symbiosis: true
  storage: true
  print: true # saves svg of network before optimization
  export: false # exports prenetwork before optimization

# optimization flags
n_flags_opt:
  print: true
  export: true
  plot: false

# Where to save single-run outputs
outputs_folder: outputs/single_analysis

# Demand flexibility
H2_profile_flag: true # 'True': the demand follows NG demand profile: 'False' it is flexible delivery during the period  (see frequency)
H2_delivery_frequency: 52 # 1: Single delivery at the end of the 'Year'. 12 : 'Month', 52: 'Week'

# RFNBOs
rfnbos_dict:
  limit: emissions         # emissions | price | None
  price_threshold: 20      # €/MWh
  emission_threshold: 0.0648   # tCO2e/MWh  (= 18 * 3.6 / 1000)

# Economics
year_EU: 2030
USD_to_EUR: 1.0
DKK_Euro: 7.46
discount_rate: 0.07