# Any content on this file will override config/n_config_default.yaml
# Use it for customization of the model


#### Enter content below this line #####
biogas: # (unit: MW CH4,  for simplicity)
  initial capacity : 30
  expansion : false
  construction_year : 2020
  remaining_investment_fraction: 0.3

H2 HP storage:
  expansion : false

onwind:
  expansion : true
  initial capacity : 15
  construction_year : 2025
  remaining_investment_fraction : 0.7
