# Any content on this file will override config/n_config_default.yaml
# Use it for customization of the model


#### Enter content below this line #####
biogas: # (unit: MW CH4,  for simplicity)
  initial capacity : 30
  expansion : false

H2 HP storage:
  expansion : false

onwind:
  expansion : false
