# config/config.yml
run_name: default_demand_full

# CO2 tax for fossil emissions and reward for negative emissions
CO2_cost: 100 # €/t (CO2_cost)

# Others
CO2_cost_ref_year: 0

# Annual Demands or price targets
# if driver == 'demand': Demands must be present AND Prices are not used in the model
# if driver == 'price': Price must be present AND Demands are set as maximum annual production (e_nom_max)
targets:
  driver: 'demand' # 'price' | 'demand'.
  demand_H2 : 270000 # MWh_H2 /y  Demand OR max production
  demand_CH4 : 260000 # Mwh_CH4 /y Demand OR max production
  demand_meoh : 36000 # Mwh_meoh /y Demand OR max production
  price_H2 : 120 # €/MWh prices are required only for driver : 'price'
  price_bioCH4 : NG_based # €/MWh can be 'NG_based' (calculated from NG price + CO2 tax) or a value.
  price_meoh : 120 # €/MWh prices are required only for driver : 'price'

# Demand flexibility - H2 grid
H2_profile_flag: false # 'True': the demand follows NG demand profile: 'False' it is flexible delivery during the period  (see frequency)
H2_delivery_frequency: 1 # ==1: Single delivery at the end of the 'Year',   ==12 : 'Month', ==52: 'Week'

# Sales of Electricity
max_RE_to_grid : 0.1 # # max share of RE production that can be sold to the grid

# Energy & Weather year
En_price_year: 2024
preprocess_flag: false

# Location
latitude: 56.566
longitude: 9.033

# Network configuration flags
n_flags:
  biogas: true
  central_heat: true
  renewables: true
  electrolysis: true
  meoh: false
  methanation: false
  symbiosis: true   # all internal connection between plants (El, H2, CO2, Heat MT, DH, LT)
  storage: true     # activate every storage (from n_config)
  print: true       # saves svg of prenetwork before optimization
  export: false     # exports prenetwork before optimization

# optimization flags
n_flags_opt:
  print: true       # saves svg of optimal network
  export: true      # exports optimal network to .nc
  plot: true

# Where to save single-run outputs
outputs_folder: outputs/single_analysis

# RFNBOs
rfnbos_dict:
  limit: 'price'         # emissions | price | unlimited | disconnected
  price_threshold: 20      # €/MWh
  emission_threshold: 0.0648   # tCO2e/MWh  (= 18 * 3.6 / 1000)

# Economics
year_EU: 2030
USD_to_EUR: 1.0
DKK_Euro: 7.46
discount_rate: 0.07

# Stochastic optimization
stochastic: false # true -> stochastic optimization across scenarios,  false -> deterministic optimization
